# Generated by Django 6.0.3 on 2026-04-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Telegram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_sync_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код синхронизации'),
        ),
    ]
