# Generated by Django 6.0.2 on 2026-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grade_letter',
            field=models.CharField(blank=True, choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], max_length=1, null=True, verbose_name='Буква'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade_number',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], null=True, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subgroup',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2')], null=True, verbose_name='Подгруппа'),
        ),
    ]
