# Generated by Django 6.0.3 on 2026-04-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='subject',
        ),
        migrations.AddField(
            model_name='appeal',
            name='contact_info',
            field=models.CharField(default='', max_length=250, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='message',
            field=models.TextField(verbose_name='Ваше заявление'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='name',
            field=models.CharField(max_length=150, verbose_name='ФИО'),
        ),
    ]
