# Generated by Django 6.0.4 on 2026-04-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_appeal_subject_appeal_contact_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAnniversary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anniversary_years', models.CharField(help_text='Например: 100 лет', max_length=50, verbose_name='Лет юбилею')),
                ('writing_year', models.CharField(help_text='Например: 1922 г.', max_length=50, verbose_name='Год написания')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание/Список книг')),
            ],
            options={
                'verbose_name': 'Книга-юбиляр',
                'verbose_name_plural': 'Книги-юбиляры',
                'ordering': ['-writing_year'],
            },
        ),
    ]
