# Generated by Django 6.0.4 on 2026-04-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше категория', verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория учителей',
                'verbose_name_plural': 'Категории учителей',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='teachers/', verbose_name='Фотография')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в списке')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='main.teachercategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'ordering': ['order'],
            },
        ),
    ]
